### ISSUE TITLE
Border colours are inverted with TempFloatingWindow display mode

### ISSUE THREAD

**Issue by maxigaz** [michaelb/sniprun#80] opened 2021-05-13 17:23 UTC
**Describe the bug**
When `display` is set to `TempFloatingWindow`, the colour of the borders and the area around them are inverted.

**To Reproduce**
1. Run `lua require'sniprun'.setup({ display = { "TempFloatingWindow" }})`
2. Highlight a passage
3. Run `:'<,'>SnipRun`

**Expected behavior**
Border colours are not inverted.

**Screenshots**
![nvim-sniprun-border](https://user-images.githubusercontent.com/10419911/118161597-10476680-b420-11eb-92bd-6b6d3f98f78e.png)

**Environment:**
 - Neovim v0.5.0-dev+1318-g61aefaf29
 - SnipRun installed through Packer
 - [nvim-solarized-lua](https://github.com/ishan9299/nvim-solarized-lua)
 - Manjaro Linux (x86-64)
 - Alacritty

**Additional context**
I've first come across the same issue in [FTerm](https://github.com/numToStr/FTerm.nvim), but I haven't been able to figure out what caused it. Borders in vim-floaterm and Telescope look fine, however.

I've tried having a clean init file (`nvim -u NORC`), changing colourschemes (to one of the built-in ones), and even a different terminal emulator (namely Kitty), but the problem same persists.

For now, being able to disable borders altogether with this display mode would be OK with me, but I don't know how to do that.

**Comment by michaelb** [comment] 2021-05-14 09:39
I'm able to reproduce, for now it looks like a colorscheme-related issue.

Sniprun relies on the FloatBorder highlight group for the styling of the floating window border, which doesn't sound so bad. 
If your colorscheme (looks like it's the case) does not define FloatBorder, it links to VertSplit, hence the 'inverted' apparence when no colorscheme, or when a colorscheme such as solarized keeps the vertical split (see [Screenshot](https://user-images.githubusercontent.com/44144536/118251648-24cf4180-b4a8-11eb-9b55-accd997b4b08.png) ) looking 'inverted' too

I'll look into what trick telescope/floaterm use, and if that's too complicated, i'll add an option to disable the border (but it's often barely visible without, depending on the colorsheme)

A temporary solution for you would be to redefine the 'FloatBorder' highlight group _after_ loading the colorscheme, like `hi FloatBorder guibg=#aa22ff guifg=#4455bb"` with values matching your background color and looking ok, and hoping it doesn't change the telescope & floaterm looks for the worse

**Comment by maxigaz** [comment] 2021-05-14 12:04
Thank you very much for looking into it!

I've just tried `hi FloatBorder guibg=#002B36 guifg=#7F9193`, and I can confirm that it works for both SnipRun and FTerm, and it doesn't affect the borders of vim-floaterm or Telescope.

**Comment by michaelb** [comment] 2021-05-14 12:18
That means they probably rely on another highlight group then.

Given that it's more like a colorscheme issue (every decent colorscheme should define FloatBorder and VertSplit correctly) than something related to sniprun, I think I'll just add an option to disable borders later in the week: imitating Telescope/floaterm will just shift the issue to another highlight group that's even less likely to be supported.

Have a good day!

**Comment by maxigaz** [comment] 2021-05-14 12:35
> If your colorscheme (looks like it's the case) does not define FloatBorder, it links to VertSplit, hence the 'inverted' apparence when no colorscheme

Oh, so that explains why I also have this behaviour with older, built-in colorschemes.

I'll report this issue to nvim-solarized-lua.

Thank you again for sharing your findings!

**Comment by maxigaz** [comment] 2021-05-14 15:25
@michaelb The issue is now fixed in nvim-solarized-lua.

**Comment by michaelb** [comment] 2021-05-14 15:28
Glad to see open-source friendly behavior on your side as well!

Leave this issue open, I'll close it when I add the option to disable borders, because that will be nice to have just in case

**Closed** 2021-05-21 21:14 UTC
Labels: bug
