### ISSUE TITLE
Terminal and Floating Window not working

### ISSUE THREAD

**Issue by yingzhu146** [michaelb/sniprun#70] opened 2021-04-25 02:39 UTC
**Describe the bug**
Both floating window and terminal don't work - I can only get the virtual text to show properly

**Classic**
Classic works
```vim
lua << EOF
require'sniprun'.setup({
  repl_enable = {'Python3_original'},
  selected_interpreters = {'Lua_nvim'},
  display = {
    "Classic"
  },
})
EOF
```
<img width="580" alt="image" src="https://user-images.githubusercontent.com/59233975/115978388-f9160700-a54c-11eb-8b12-a981808596d3.png">

**Terminal**
Terminal is blank
```vim
lua << EOF
require'sniprun'.setup({
  repl_enable = {'Python3_original'},
  selected_interpreters = {'Lua_nvim'},
  display = {
    "Terminal"
  },
})
EOF
```
<img width="763" alt="image" src="https://user-images.githubusercontent.com/59233975/115978382-e4397380-a54c-11eb-8532-51c63a627e6b.png">

**Temporary Floatterm**

```vim
lua << EOF
require'sniprun'.setup({
  repl_enable = {'Python3_original'},
  selected_interpreters = {'Lua_nvim'},
  display = {
    "VirtualTextOk",
    "VirtualTextErr",
    "TempFloatingWindow"
  },
})
EOF
```

<img width="516" alt="image" src="https://user-images.githubusercontent.com/59233975/115978443-675ac980-a54d-11eb-89ca-5ac76afe8d7c.png">

and

```vim
lua << EOF
require'sniprun'.setup({
  repl_enable = {'Python3_original'},
  selected_interpreters = {'Lua_nvim'},
  display = {
    "VirtualTextOk",
    "VirtualTextErr",
    "LongTempFloatingWindow"
  },
})
EOF
 ```
<img width="561" alt="image" src="https://user-images.githubusercontent.com/59233975/115978496-c4ef1600-a54d-11eb-82eb-48fe388d7383.png">

**Environment:**
 - Neovim version 0.5.0

**Comment by yingzhu146** [comment] 2021-04-25 02:40
No rush here, and apologies for spamming with all the issues and feature requests :)

**Comment by michaelb** [comment] 2021-04-25 05:47
No worries, although it's starting to becoming a lot of stuff that doesn't work right on machines other than mine. (Worrying)

There are two bugs I have fixed in dev, one that prevented the default configuration from being completely overridden by a custom one, and another that misplaced a bit floating windows, and if run on the last line it would fail to display it.

I admit having tested superficially those display modes (only that they worked) up to yesterday, and I'm currently in the process of fine-tuning their behavior


The fix may not cover your two issues, especially the 'Terminal' one but that will be a step in the good direction.

**Comment by yingzhu146** [comment] 2021-04-25 13:54
Yeah - I think part of this might be that everybody is using their own compiled Neovim instances until 0.5.0 is released :/ 
I had to jump through a lot of hoops to get it working correctly on the M1 and run natively.

Just reinstalled in and tried it - neither Terminal nor Floating Window is working.

Just to make sure I'm not being simply too dense - can you post the config to reproduce https://github.com/michaelb/sniprun/blob/10e43bee5f576bb1e8ead2c6cebe4868bb9509f1/ressources/visual_assets/floating_window.png
(might be worth adding to https://github.com/michaelb/sniprun/blob/10e43bee5f576bb1e8ead2c6cebe4868bb9509f1/ressources/display_floating_window.md and the others)

**Comment by michaelb** [comment] 2021-04-25 18:41
There should not be anything wrong. My own config right now looks like this and it's able to display all that at the same time, and by deleting any of the lines the behavior still matches what's expected. I tested on the file that's on the screenshots, on the print('lol').

I'm also on latest master but maybe there are deeper things between my x86 Arch and your ARM Mac... Out of my scope and skill, unfortunately.

Do you still have no log file at ~/.cache/sniprun/sniprun.log ? It may help debugging, especially if it shows a crash (incomplete output) during display in Terminal or FloatingWindow mode

```
require'sniprun'.setup({
  repl_enable = {'Python3_original'},
  selected_interpreters = {'Lua_nvim'},

  display = {
    "VirtualTextOk",
    "VirtualTextErr",
    "TempFloatingWindow",
    "Terminal"
  },
})
```

**Comment by yingzhu146** [comment] 2021-04-26 04:34
No log file no - does Neovim or the rust runtime offer a simple way for me to help the debugging in any way?

**Comment by michaelb** [comment] 2021-04-26 06:23
Unfortunately, since the Rust binary communicate via RPC over stdio, there is no way to 'print' something, the log file is the only way.

I wonder if the log exists, but just not at the same path as on Linux ? I use the dir-rs crate to (supposedly) be cross-compatible. Maybe the XDG cache location is different on Mac ? (like ~/Library/Caches ?)

I'll probably need this log file (impossible to do anything without) content after only one 'SnipRun' to have any  chance of fixing this

**Comment by yingzhu146** [comment] 2021-04-26 12:36
[sniprun.log](https://github.com/michaelb/sniprun/files/6377031/sniprun.log)
There you go - indeed was at the location you said

**Comment by michaelb** [comment] 2021-04-26 12:48
Okay, very insightful and exactly what I was looking for!

Unfortunately, its content means that, for some strange reason, your neovim instance does not support:
- a key 'border' in [nvim_open_win()](https://neovim.io/doc/user/api.html#nvim_open_win())
- [nvim_open_term](https://neovim.io/doc/user/api.html#nvim_open_term())

While these two are not exactly new, I really can't fix something that: borders are a must for the floating window to be visible, and the the 2nd __is__ the entry point to open a terminal.

I'll think a bit about how if it's possible to workaround something, but the odds are very low, honestly

**Comment by yingzhu146** [comment] 2021-04-26 21:26
I can recompile it and see if that will get rid of it - might be weekend until I get around it though.

I do use quite a few other plugins with floating windows (or at least think so, like Floatterm, Fzfvim, Clap, Telescope, coc-nvim) though so I'm surprised this only comes up now. Not to say you shouldn't use it - but these plugins might provide example ways to solve it in case many users might face this issue (which is an untested hypothesis)

**Comment by michaelb** [comment] 2021-04-26 22:57
You're right that telescope at least should use the same interface (nvim_open_win) as sniprun, and ask for the same 'border' argument. Maybe they have more advanced error handling or use things deeper than the API?

Anyway, this is getting a bit out of hand. 
Bluntly speaking, I won't be able to continue debugging remotely things this complicated, and while i'm concerned and saddened that it doesn't work right for you (especially since those features were requested by you... honestly I neither want or can (i mean should, both the project and myself) invest more ressources in bug-hunting this.

If the problem is actually widespread, that'll become another story, though that won't make fixing this easier; and by all means, if you find a solution document it (here, or if relevant, on the neovim repo)


bdf7e7ea5a7c9e2fae2b928119c73d2ca98fe229

**Comment by yingzhu146** [comment] 2021-04-27 00:21
completely understandable and agree with your priority setting!

**Comment by michaelb** [comment] 2021-04-27 06:45
Thanks for your understanding :-)

**Closed by michaelb** 2021-04-27 06:45 UTC
Labels: bug, wontfix
