### ISSUE TITLE
Python 3: indentation and syntax error

### ISSUE THREAD

**Issue by joalof** [michaelb/sniprun#193] opened 2022-11-03 20:55 UTC
**Describe the bug**
Thanks for writing this awesome plugin! I'm having some issues with executing code using the ` Python3 fifo` interpreter. Basically, trying to execute a snippet that includes an indented code block (tested for function definition, for-loops etc) + any number of following statements will result in a syntax error. Separately executing first the indented block and then the following statement works, however, so maybe this is related to how indentations are handled.

**To Reproduce**
1. Crete a python file with the MRE below.
2. Select all and run `:'<,'>SnipRun`. Also occurs if you do `gg<YourSnipRunOperator>G`
3. Results in the following error:
```
RuntimeError:     foo()
    ^^^     
SyntaxError: invalid syntax
```

**Expected behavior**
The code should run correctly. 

**Minimal reproducible example**
```python
def foo():
    print('bar')

foo()
```
**Environment:**
 - Neovim version: `NVIM v0.8.0-v0.8.0` (Release build)
- OS/distribution:  `Ubuntu 22.04.1 LTS` (via WSL2)

**Additional context**
Occurs for the ` Python3 fifo`  interpreter.

**Comment by michaelb** [comment] 2022-11-03 22:00
Indeed, I was half-aware that this kind of bug could exist. The current implementation fixes (though not entirely it seems) a annoying corner case of the python interpreter taking input from a pipe by removing blank lines (interpreted like an 'enter').

Without this fix, things like
```
def foo:
     print("bar")

    # blank line above
    print("ok")
```

will be understood by the python interpreter as
```
def foo():
    print("bar")
```
then (re-indetnted because sniprun normalize indentation,<- this works as intended)

```
print("ok")
```

I think I have some idea of how to fix it, by replacing my ugly fix by an even uglier one: replacing all blank lines by "\".
Indeed, (and you can try it yourself), if you add backslashes at the beginning of your blank lines, `:%SnipRun` (which btw may be more practical than `gg<SnipRunOperator>G` ) will succeed as it should. Discovered this right now. 

I'll draft up a quick PR over the weekend, and I hope the neorg support ( #191 ) will be ready by then so I can merge all those changes into the v1.2.8 release. (normal sniprun users who don't compile the binary themselves are dependent on the release to get the new features)

**Comment by joalof** [comment] 2022-11-05 00:11
Thanks for looking into this. Hmm so you mean
```python
def foo:
     print("bar")
\
foo()
```
? If I send this I get neither output nor an error.

**Comment by michaelb** [comment] 2022-11-05 10:50
Hmm the actual requirements are a bit more complex than that actually, my bad.

Adding manually the necessary indentation seems to work, so I'll probably go with that. (still needs testing though)

![image](https://user-images.githubusercontent.com/44144536/200116296-a3ac770c-68f2-4c54-90e5-2a7a91f95a23.png)

**Comment by michaelb** [comment] 2022-11-05 13:39
The v1.2.8 release is out and satisfying to me. Please try it out !

**Comment by joalof** [comment] 2022-11-05 17:25
Thanks! This fixes the original issue, but has introduced a new bug: the first time you send any import statement you will get an error (only occurs on the first send though, on the second it runs correctly)
```
RuntimeError:                                                                                                                                      
    ^                                                                                                                                                                                         
SyntaxError: expected 'except' or 'finally' block                                                                                                                                             
  File "<stdin>", line 1                                                                                                                                                                      
    except:                                                                                                                                                                                   
    ^^^^^^                                                                                                                                                                                    
SyntaxError: invalid syntax                                                                                                                                                                   
  File "<stdin>", line 1                                                                                                                                                                      
    pass                                                                                                                                                                                      
IndentationError: unexpected indent
```

**Comment by michaelb** [comment] 2022-11-05 17:36
Will be fixed in the next release then thanks

Nota bene: you don't need to include your import statements. Python3_fifo (and a handful of others) can detect and import the needed modules by themselves.... So this will be a low-priority bug😉

**Comment by michaelb** [comment] 2022-11-05 18:09
Actually the issue reaches every try-catch bloc (which are used to 'safely' do imports). Working on it

**Closed by michaelb** 2022-11-05 18:09 UTC
Labels: bug
