### ISSUE TITLE
C + + language has no effect

### ISSUE THREAD

**Issue by denstiny** [michaelb/sniprun#45] opened 2021-03-12 14:55 UTC

**Comment by michaelb** [comment] 2021-03-14 09:42
hmmm, very strange... 
I just tested to run sniprun on a simple
std::cout << "Hello World!"; 
and it worked :-o

Which compilers do you have installed and what are you trying to run? If any, what error is displayed?

**Comment by denstiny** [comment] 2021-03-14 11:51
I installed the g + + and GCC, I found it is using c + + as the c language, and output in the form of c language, that is to say, he could not identify cout

**Comment by denstiny** [comment] 2021-03-14 11:58
Uploading 2021-03-14_19-56-44.mp4…

**Comment by denstiny** [comment] 2021-03-14 11:58
https://user-images.githubusercontent.com/57088952/111067515-a4b84a00-84ff-11eb-9040-27b525c33c56.mp4

**Comment by michaelb** [comment] 2021-03-14 12:56
ohh I see what's going wrong.

(First and foremost, excuse me for I have little experience with C++)

What's going wrong here is that sniprun does not know you're using the namespace std. It can obviously be added to the code sniprun generates, just like the #include <iostream> and other boilerplate. 

However, I don't know if that would be a good solution. Is std always 'namespaced' (?) like this ? 

An intermediate solution would be to look in the file for all the 'namespace' keywords and add all those to the generated code; would that be ok, and do you think it could create issues with some edge cases?

**Comment by michaelb** [comment] 2021-03-14 13:00
also, for the question of identifying languages, sniprun relies on Neovim to give the filetype. Neovim associate *.c files with the C language, and the *.cpp files as C++. It's not really sniprun responsiblity to correctly identify the filetype, though I have to ideas for the distant future to improve that.

**Comment by michaelb** [comment] 2021-03-14 14:36
I've done some research and C++ was upgraded to a full Import support level as of v0.4.8

That means your example with namespaces works correctly, and that you can now also use functions from <math.h>, or <stdint> (These imports are auto-imported), though not #include "yourlocalheader.h"

You can close the issue if updating grant expected behavior, or anyway i'll do it some time from now.

**Comment by denstiny** [comment] 2021-03-14 14:38
Oh, I'm sorry, I also am a c + + beginners, at least I see most of people are doing this

**Comment by denstiny** [comment] 2021-03-14 14:39
I have an idea that can run a function, in order to debug the function whether can very good use

**Comment by michaelb** [comment] 2021-03-14 14:41
No worries! (Sniprun is also somewhat oriented towards non-experts)

Anyway, use cases similar to your example should work now.

I have not understood your last comment, would you mind developping (and if off-topic with this issue, developping elsewhere? - another issue, or the discussion section)

**Comment by denstiny** [comment] 2021-03-14 14:44
Uploading 2021-03-14_22-43-35.mp4…

**Comment by denstiny** [comment] 2021-03-14 14:45
https://user-images.githubusercontent.com/57088952/111072753-e86a7e00-8516-11eb-9cdd-b25d2dee07a7.mp4

**Comment by denstiny** [comment] 2021-03-14 14:46
> 不用担心！（Sniprun在某种程度上也面向非专家）
> 
> 无论如何，与您的示例相似的用例现在应该可以工作。
> 
> 我不明白您的最后评论，您会介意发展吗？（如果这个问题离题，则发展到其他地方？-另一个问题或讨论部分）

I'm sorry my English is not good, I'm using translation and speak

**Comment by denstiny** [comment] 2021-03-14 14:49
If can run normally on the video, I think this plugin will go farther, for now, function is not so practical, sorry if you forgive me more objective, but I also for the future of plug-in

**Comment by michaelb** [comment] 2021-03-14 14:51
We should move over a new issue #47 , which i'll open for you, since this is something else (though not completely unrelated).

(Because this is a C (not a C++ file), there is no support for includes!)

**Closed** 2021-03-14 15:19 UTC
Labels: bug
