### ISSUE TITLE
JS_TS_deno `Interpreter limitation error: reached the 30s timeout`

### ISSUE THREAD

**Issue by eggers** [michaelb/sniprun#176] opened 2022-08-30 20:50 UTC
**Describe the bug**

I'm not able to get the `JS_TS_deno` interpreter working. The default interpreter works. When run my code, it just times out. Additionally there is no `:SnipInfo JS_TS_deno`

**What do the bug concerns? Sniprun itself, a particular interpreter?**

The `JS_TS_deno` interpreter, the `TypeScript_original` interpreter works fine, but no REPL

**To Reproduce**
1. Enable the JS_TS_deno interpreter
2. Open a typescript file
3. type: `console.log('anything');`
4. execute :SnipRun

**Expected behavior**
Code should excute and return results

**Screenshots**

```
  ---------------ERROR---------------
> console.log('asdf');
Deno kernel launched, re-run your sni


  -------------------------ERROR--------------------------
> console.log('asdf');
Interpreter limitation error: reached the 30s timeout
```

**Environment:**
 - :version
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
```

- OS/distribution MacBook Pro M1 Pro OSX12.4

**Comment by michaelb** [comment] 2022-09-01 06:46
Hey! Quite the bug indeed

Are you sure (just in case, because I forgot to document it, and the symptoms are similars on my machine if i uninstall it) that you have the 'deno' package installed (and working) on your computer?

Can you run 'deno repl' and use the REPL without any issue?


If so, there still may be an issue with sniprun, in which case, you'd do well to send me a log (located at $XDG_CACHE/sniprun/sniprun.log) after a single problematic run, and since it's a REPL-capable, I could use the contents of the js-ts-deno directory at the same cache location

**Comment by eggers** [comment] 2022-09-02 04:15
thanks for looking into this. I do have deno, I double checked that it worked since I only installed it for sniprun:

```
[00:00:00.000] (204f4d600) INFO   [MAIN] SnipRun launched successfully
[00:00:00.000] (204f4d600) INFO   [MAIN] Start of main event loop
[00:00:00.000] (204f4d600) INFO   EVENT 1 RECEIVED ##################
[00:00:00.000] (204f4d600) INFO   [MAINLOOP] Run command received
[00:00:00.000] (204f4d600) INFO   [RUN] clone event handler
[00:00:00.000] (30de5a000) INFO   [RUN] spawned thread
[00:00:00.000] (30de5a000) INFO   [FILLDATA] got back eventual interpreter data
[00:00:00.000] (30de5a000) INFO   values length: 4
[00:00:00.000] (30de5a000) INFO   cli arguments are not a string: String(Utf8String { s: Ok("") })
[00:00:00.000] (30de5a000) INFO   got data range: [1, 1]
[00:00:00.000] (30de5a000) INFO   looped on key sniprun_root_dir
[00:00:00.001] (30de5a000) INFO   [FILLDATA] got sniprun root
[00:00:00.002] (30de5a000) INFO   [FILLDATA] got filetype
[00:00:00.003] (30de5a000) INFO   [FILLDATA] got current_line
[00:00:00.006] (30de5a000) INFO   [FILLDATA] got current_bloc
[00:00:00.007] (30de5a000) INFO   [FILLDATA] got filepath
[00:00:00.007] (30de5a000) INFO   [FILLDATA] got nvim_instance
[00:00:00.007] (30de5a000) INFO   looped on key selected_interpreters
[00:00:00.007] (30de5a000) INFO   [FILLDATA] got selected interpreters
[00:00:00.007] (30de5a000) INFO   looped on key repl_enable
[00:00:00.007] (30de5a000) INFO   [FILLDATA] got repl enabled interpreters
[00:00:00.008] (30de5a000) INFO   looped on key repl_disable
[00:00:00.008] (30de5a000) INFO   [FILLDATA] got repl disabled interpreters
[00:00:00.008] (30de5a000) INFO   looped on key display
[00:00:00.008] (30de5a000) INFO   [FILLDATA] display type found : Ok(TerminalWithCode)
[00:00:00.008] (30de5a000) INFO   [FILLDATA] got display types
[00:00:00.008] (30de5a000) INFO   looped on key show_no_output
[00:00:00.008] (30de5a000) INFO   [FILLDATA] display type with 'no output'on found : Ok(Classic)
[00:00:00.008] (30de5a000) INFO   [FILLDATA] display type with 'no output'on found : Ok(TempFloatingWindow)
[00:00:00.008] (30de5a000) INFO   [FILLDATA] got show_no_output
[00:00:00.008] (30de5a000) INFO   looped on key inline_messages
[00:00:00.008] (30de5a000) INFO   [FILLDATA] got inline_messages setting
[00:00:00.008] (30de5a000) INFO   looped on key neovim_pid
[00:00:00.008] (30de5a000) INFO   [FILLDATA] got neovim_pid value setting: 44663
[00:00:00.008] (30de5a000) INFO   [FILLDATA] Done!
[00:00:00.009] (30de5a000) INFO   [OVERRIDE] No data to override
[00:00:00.009] (30de5a000) INFO   [RUN] filled dataholder
[00:00:00.009] (30de5a000) INFO   [RUN] created launcher
[00:00:00.009] (30de5a000) INFO   selected JS_TS_deno
[00:00:00.009] (30de5a000) INFO   [LAUNCHER] Selected interpreter: JS_TS_deno, at level Selected
[00:00:00.009] (30de5a000) INFO   Checking cli-args: []
[00:00:00.009] (30de5a000) INFO   REPL enabled
[00:00:00.009] (30de5a000) INFO   reading previous code
[00:00:00.009] (30de5a000) INFO   found interpreter_data
[00:00:00.009] (30de5a000) INFO   launching kernel : "/Users/jeggers/.vim/plugged/sniprun/lua/../ressources/init_repl.sh" on "/Users/jeggers/Library/Caches/sniprun/js-ts_deno/44663"
[00:00:00.116] (30de5a000) INFO   reading previous code
[00:00:00.116] (30de5a000) INFO   found interpreter_data
[00:00:00.116] (30de5a000) INFO   reading previous code
[00:00:00.116] (30de5a000) INFO   found interpreter_data
[00:00:00.116] (30de5a000) INFO   code saved: 
kernel_launched

[00:00:00.116] (30de5a000) INFO   [RUN] Interpreter return a result
[00:00:00.116] (30de5a000) INFO   Display type chosen: [TerminalWithCode]
[00:00:00.116] (30de5a000) INFO   message 'Deno kernel launched, re-run your snippet' cleaned out
[00:00:00.117] (30de5a000) INFO   reading previous code
[00:00:00.117] (30de5a000) INFO   found interpreter_data
[00:00:00.117] (30de5a000) INFO   reading previous code
[00:00:00.117] (30de5a000) INFO   found interpreter_data
[00:00:00.117] (30de5a000) INFO   code saved: 
kernel_launched

[00:00:00.117] (30de5a000) INFO   [RUN] Interpreter return a result
[00:00:00.117] (30de5a000) INFO   Display type chosen: [TerminalWithCode]
[00:00:00.118] (30de5a000) INFO   message 'Deno kernel launched, re-run your snippet' cleaned out
[00:00:00.168] (30de5a000) INFO   display terminal res = Ok(())
[00:00:05.117] (30de5a000) INFO   display terminal res = Err(GenericError("Wait timeout (nvim_command)"))
[00:00:06.403] (204f4d600) INFO   EVENT 2 RECEIVED ##################
[00:00:06.403] (204f4d600) INFO   [MAINLOOP] Run command received
[00:00:06.403] (204f4d600) INFO   [RUN] clone event handler
[00:00:06.403] (30e05d000) INFO   [RUN] spawned thread
[00:00:06.403] (30e05d000) INFO   [FILLDATA] got back eventual interpreter data
[00:00:06.403] (30e05d000) INFO   values length: 4
[00:00:06.403] (30e05d000) INFO   cli arguments are not a string: String(Utf8String { s: Ok("") })
[00:00:06.403] (30e05d000) INFO   got data range: [1, 1]
[00:00:06.403] (30e05d000) INFO   looped on key sniprun_root_dir
[00:00:06.403] (30e05d000) INFO   [FILLDATA] got sniprun root
[00:00:06.405] (30e05d000) INFO   [FILLDATA] got filetype
[00:00:06.406] (30e05d000) INFO   [FILLDATA] got current_line
[00:00:06.409] (30e05d000) INFO   [FILLDATA] got current_bloc
[00:00:06.410] (30e05d000) INFO   [FILLDATA] got filepath
[00:00:06.410] (30e05d000) INFO   [FILLDATA] got nvim_instance
[00:00:06.410] (30e05d000) INFO   looped on key selected_interpreters
[00:00:06.410] (30e05d000) INFO   [FILLDATA] got selected interpreters
[00:00:06.410] (30e05d000) INFO   looped on key repl_enable
[00:00:06.410] (30e05d000) INFO   [FILLDATA] got repl enabled interpreters
[00:00:06.410] (30e05d000) INFO   looped on key repl_disable
[00:00:06.410] (30e05d000) INFO   [FILLDATA] got repl disabled interpreters
[00:00:06.410] (30e05d000) INFO   looped on key display
[00:00:06.410] (30e05d000) INFO   [FILLDATA] display type found : Ok(TerminalWithCode)
[00:00:06.410] (30e05d000) INFO   [FILLDATA] got display types
[00:00:06.410] (30e05d000) INFO   looped on key show_no_output
[00:00:06.410] (30e05d000) INFO   [FILLDATA] display type with 'no output'on found : Ok(Classic)
[00:00:06.410] (30e05d000) INFO   [FILLDATA] display type with 'no output'on found : Ok(TempFloatingWindow)
[00:00:06.410] (30e05d000) INFO   [FILLDATA] got show_no_output
[00:00:06.410] (30e05d000) INFO   looped on key inline_messages
[00:00:06.410] (30e05d000) INFO   [FILLDATA] got inline_messages setting
[00:00:06.410] (30e05d000) INFO   looped on key neovim_pid
[00:00:06.411] (30e05d000) INFO   [FILLDATA] got neovim_pid value setting: 44663
[00:00:06.411] (30e05d000) INFO   [FILLDATA] Done!
[00:00:06.411] (30e05d000) INFO   [OVERRIDE] No data to override
[00:00:06.411] (30e05d000) INFO   [RUN] filled dataholder
[00:00:06.411] (30e05d000) INFO   [RUN] created launcher
[00:00:06.411] (30e05d000) INFO   selected JS_TS_deno
[00:00:06.411] (30e05d000) INFO   [LAUNCHER] Selected interpreter: JS_TS_deno, at level Selected
[00:00:06.411] (30e05d000) INFO   Checking cli-args: []
[00:00:06.411] (30e05d000) INFO   REPL enabled
[00:00:06.411] (30e05d000) INFO   reading previous code
[00:00:06.411] (30e05d000) INFO   found interpreter_data
[00:00:06.411] (30e05d000) INFO   Deno kernel already running
[00:00:06.411] (30e05d000) INFO   javascript/typescript self.code) = console.log('asdf')
[00:00:06.413] (30e05d000) INFO   running launcher /Users/jeggers/.vim/plugged/sniprun/lua/../ressources/launcher_repl.sh
[00:00:06.414] (30e05d000) INFO   cmd status: Ok(Child { stdin: None, stdout: None, stderr: None, .. })
[00:00:06.414] (30e05d000) INFO   outfile : "/Users/jeggers/Library/Caches/sniprun/js-ts_deno/44663/fifo_repl/out_file"
[00:00:06.414] (30e05d000) INFO   searching for things between "sniprun_started_id=1" and "sniprun_finished_id=1"
[00:00:06.467] (30e05d000) INFO   not found yet
[00:00:06.571] (30e05d000) INFO   not found yet
[00:00:06.726] (30e05d000) INFO   not found yet
[00:00:06.931] (30e05d000) INFO   not found yet
[00:00:07.186] (30e05d000) INFO   not found yet
[00:00:07.489] (30e05d000) INFO   not found yet
[00:00:07.844] (30e05d000) INFO   not found yet
[00:00:08.249] (30e05d000) INFO   not found yet
[00:00:08.704] (30e05d000) INFO   not found yet
[00:00:09.206] (30e05d000) INFO   not found yet
[00:00:09.761] (30e05d000) INFO   not found yet
[00:00:10.363] (30e05d000) INFO   not found yet
[00:00:11.018] (30e05d000) INFO   not found yet
[00:00:11.722] (30e05d000) INFO   not found yet
[00:00:12.477] (30e05d000) INFO   not found yet
[00:00:13.283] (30e05d000) INFO   not found yet
[00:00:14.138] (30e05d000) INFO   not found yet
[00:00:15.043] (30e05d000) INFO   not found yet
[00:00:15.997] (30e05d000) INFO   not found yet
[00:00:17.002] (30e05d000) INFO   not found yet
[00:00:18.056] (30e05d000) INFO   not found yet
[00:00:19.161] (30e05d000) INFO   not found yet
[00:00:20.316] (30e05d000) INFO   not found yet
[00:00:21.521] (30e05d000) INFO   not found yet
[00:00:22.776] (30e05d000) INFO   not found yet
[00:00:24.082] (30e05d000) INFO   not found yet
[00:00:25.437] (30e05d000) INFO   not found yet
[00:00:26.842] (30e05d000) INFO   not found yet
[00:00:28.297] (30e05d000) INFO   not found yet
[00:00:29.803] (30e05d000) INFO   not found yet
[00:00:31.353] (30e05d000) INFO   not found yet
[00:00:32.959] (30e05d000) INFO   not found yet
[00:00:34.614] (30e05d000) INFO   not found yet
[00:00:36.316] (30e05d000) INFO   not found yet
[00:00:38.071] (30e05d000) INFO   [RUN] Interpreter return a result
[00:00:38.071] (30e05d000) INFO   Display type chosen: [TerminalWithCode]
[00:00:38.071] (30e05d000) INFO   message 'Interpreter limitation error: reached the 30s timeout' cleaned out
[00:00:38.072] (30e05d000) INFO   display terminal res = Ok(())
```

I did check if there was an out file in js-ts_deno. None of the directories do. Here's the result of tree:

```
Library/Caches/sniprun/js-ts_deno
├── 11637
├── 11854
├── 41700
├── 44080
├── 44663
├── 9539
└── main.ts
```

and main.ts if it's helpful:

```typescript

console.log("sniprun_started_id=1")

console.error("sniprun_started_id=1")

console.log('asdf')


console.log("sniprun_finished_id=1")

console.error("sniprun_finished_id=1")
```

**Comment by michaelb** [comment] 2022-09-03 14:20
A few more questions, and long shot at a fix (I'm unable to reproduce the issue on my linux laptop, even with the same neovim version and same display settings)

You pasted "Deno kernel launched, re-run your sni" in your first message. Was that your copy-paste or is a part of the sentence missing ? That would be coherent with my guess of the underlying issue.

Could you try installing from the new `macos-close-fd-after-fork` branch and report back ? This a potentially dangerous fix and I can't quite test on mac machine myself 

<details><summary>technical stuff about the issue in case you're curious</summary>

For almost all REPL-capable interpreters, including the one you're trying to use, sniprun forks itself to the background, and use this new process to run the interpreter, in a `Command::new("deno").args(&["repl", "-q"])` fashion, with some bash shenanigans to redirect stdout and stderr that future sniprun runs (from the parent process) will observe.

on UNIX* platforms, by default fork()ing keeps all files decriptors open; including unexpected things like logs (which is why we're having twice the logs sometimes) and maybe the sockets used by the RPC communication between sniprun and neovim... Thus potentially having a conflict between the parent process (who has to use the RPC channel to communicate to neovim) and the child process (which should have nothing to say, and only run the REPL, but currently, keeps the socket open)

Linux uses a close-on-exec flag when it forks, making subsequent calls to exec() close the file descriptors in the child process, but that may be handled differently on MacOS, and what is 'exec' in Rust may be ill-defined. It may also be a race condition that occurs more easily on your machine.

I'll be adding a fix that close all open fd when forking to the background, that fixes the double logging and, hopefully, that thing with the RPC channel

</details>

**Comment by eggers** [comment] 2022-09-04 23:11
I think it was just a copy paste issue. I'm seeing the full `Deno kernel launched, re-run your snippet` text when I rerun the test. 

I tested that branch, and it didn't work either. I also tried the Python3_fifo and experienced similar timeouts. So I did some more diagnostics. I tracked down the issue to:

```
while pkill -0 nvim ;do
    sleep 1
done
```

I noticed that when I start nvim with my vi alias, `pkill -0 nvim` returns false in dummy script. However, even when I start nvim with `nvim`, `pkill -0 nvim` still returns false inside of init_repl.sh. Is there another way that we can test for the prescence of nvim running?

**Comment by eggers** [comment] 2022-09-05 03:47
Ok, so it was a symlink, not an alias. Replacing the symlink with an alias works... but strangely, only if I have multiple nvim processes running

**Comment by michaelb** [comment] 2022-09-05 06:23
Wow, thanks!

> Is there another way that we can test for the prescence of nvim running?

That's the question. On Linux, pkill -0 is the (one of the) _de facto_ way(s), that's been working since the beginning. MacOS strikes again....?

Though, it wouldn't work if you symlinked anything to 'nvim'. While people mostly alias, but it'd be nice to handle that case as well


Since i can easily get the nvim instance' PID, I hope that a `while pkill -0 $PID` in the script will be a definitive (and better) solution. I'll try doing that asap.


A little warning: commenting the pkill will have 'deno' sessions running as long as your PC is on (or until a pkill deno), so if you've been testing for some time you may have a lot of these

**Comment by eggers** [comment] 2022-09-05 08:05
Thanks for the heads up, and thanks for the great work on this plugin.

**Comment by michaelb** [comment] 2022-09-05 20:13
Things have been ironed out on the dev branch, overall the thing is much cleaner, and, hopefully, work on MacOS. 

I now rely on the existence of the PID the neovim instance got (`ps -p $nvim_pid` ) to determine whether the REPL process should be dropped. The  'dev' branch has everything worked out, if you could confirm it works that would be great!

There's also a log specific to the REPL initialisation script, at a path that doesn't get deleted this time, so there's that for easier debugging in case it's still needed, and I'd be interested in the $XDG_CACHE/sniprun/sniprun.log file after a REPL run of a simple print, if you don't mind.

**Comment by eggers** [comment] 2022-09-06 16:53
Works! Thank you.

```
[00:00:00.000] (2048e9600) INFO   [MAIN] SnipRun launched successfully
[00:00:00.000] (2048e9600) INFO   [MAIN] Start of main event loop
[00:00:00.000] (2048e9600) INFO   EVENT 1 RECEIVED ##################
[00:00:00.000] (2048e9600) INFO   [MAINLOOP] Run command received
[00:00:00.000] (2048e9600) INFO   [RUN] clone event handler
[00:00:00.000] (30d37b000) INFO   [RUN] spawned thread
[00:00:00.000] (30d37b000) INFO   [FILLDATA] got back eventual interpreter data
[00:00:00.000] (30d37b000) INFO   values length: 4
[00:00:00.000] (30d37b000) INFO   cli arguments are not a string: String(Utf8String { s: Ok("") })
[00:00:00.000] (30d37b000) INFO   got data range: [2, 2]
[00:00:00.000] (30d37b000) INFO   looped on key sniprun_root_dir
[00:00:00.000] (30d37b000) INFO   [FILLDATA] got sniprun root
[00:00:00.002] (30d37b000) INFO   [FILLDATA] got filetype
[00:00:00.003] (30d37b000) INFO   [FILLDATA] got current_line
[00:00:00.006] (30d37b000) INFO   [FILLDATA] got current_bloc
[00:00:00.007] (30d37b000) INFO   [FILLDATA] got filepath
[00:00:00.007] (30d37b000) INFO   [FILLDATA] got nvim_instance
[00:00:00.007] (30d37b000) INFO   looped on key selected_interpreters
[00:00:00.007] (30d37b000) INFO   [FILLDATA] got selected interpreters
[00:00:00.007] (30d37b000) INFO   looped on key repl_enable
[00:00:00.007] (30d37b000) INFO   [FILLDATA] got repl enabled interpreters
[00:00:00.007] (30d37b000) INFO   looped on key repl_disable
[00:00:00.007] (30d37b000) INFO   [FILLDATA] got repl disabled interpreters
[00:00:00.007] (30d37b000) INFO   looped on key display
[00:00:00.007] (30d37b000) INFO   [FILLDATA] display type found : Ok(TerminalWithCode)
[00:00:00.007] (30d37b000) INFO   [FILLDATA] got display types
[00:00:00.007] (30d37b000) INFO   looped on key show_no_output
[00:00:00.007] (30d37b000) INFO   [FILLDATA] display type with 'no output'on found : Ok(Classic)
[00:00:00.007] (30d37b000) INFO   [FILLDATA] display type with 'no output'on found : Ok(TempFloatingWindow)
[00:00:00.007] (30d37b000) INFO   [FILLDATA] got show_no_output
[00:00:00.007] (30d37b000) INFO   looped on key inline_messages
[00:00:00.008] (30d37b000) INFO   [FILLDATA] got inline_messages setting
[00:00:00.008] (30d37b000) INFO   looped on key neovim_pid
[00:00:00.008] (30d37b000) INFO   [FILLDATA] got neovim_pid value setting: 29553
[00:00:00.008] (30d37b000) INFO   [FILLDATA] Done!
[00:00:00.008] (30d37b000) INFO   [OVERRIDE] No data to override
[00:00:00.008] (30d37b000) INFO   [RUN] filled dataholder
[00:00:00.008] (30d37b000) INFO   [RUN] created launcher
[00:00:00.008] (30d37b000) INFO   selected JS_TS_deno
[00:00:00.008] (30d37b000) INFO   [LAUNCHER] Selected interpreter: JS_TS_deno, at level Selected
[00:00:00.008] (30d37b000) INFO   Checking cli-args: []
[00:00:00.008] (30d37b000) INFO   REPL enabled
[00:00:00.008] (30d37b000) INFO   reading previous code
[00:00:00.008] (30d37b000) INFO   found interpreter_data
[00:00:00.008] (30d37b000) INFO   launching kernel : "/Users/jeggers/.vim/plugged/sniprun/lua/../ressources/init_repl.sh" on "/Users/jeggers/Library/Caches/sniprun/js-ts_deno/29553"
[00:00:00.116] (30d37b000) INFO   reading previous code
[00:00:00.116] (30d37b000) INFO   found interpreter_data
[00:00:00.116] (30d37b000) INFO   reading previous code
[00:00:00.116] (30d37b000) INFO   found interpreter_data
[00:00:00.116] (30d37b000) INFO   code saved: 
kernel_launched

[00:00:00.116] (30d37b000) INFO   [RUN] Interpreter return a result
[00:00:00.116] (30d37b000) INFO   Display type chosen: [TerminalWithCode]
[00:00:00.116] (30d37b000) INFO   message 'Deno kernel launched, re-run your snippet' cleaned out
[00:00:00.121] (30d37b000) INFO   display terminal res = Ok(())
[00:00:02.494] (2048e9600) INFO   EVENT 2 RECEIVED ##################
[00:00:02.494] (2048e9600) INFO   [MAINLOOP] Run command received
[00:00:02.494] (2048e9600) INFO   [RUN] clone event handler
[00:00:02.495] (30d57e000) INFO   [RUN] spawned thread
[00:00:02.495] (30d57e000) INFO   [FILLDATA] got back eventual interpreter data
[00:00:02.495] (30d57e000) INFO   values length: 4
[00:00:02.495] (30d57e000) INFO   cli arguments are not a string: String(Utf8String { s: Ok("") })
[00:00:02.495] (30d57e000) INFO   got data range: [2, 2]
[00:00:02.495] (30d57e000) INFO   looped on key sniprun_root_dir
[00:00:02.496] (30d57e000) INFO   [FILLDATA] got sniprun root
[00:00:02.497] (30d57e000) INFO   [FILLDATA] got filetype
[00:00:02.498] (30d57e000) INFO   [FILLDATA] got current_line
[00:00:02.501] (30d57e000) INFO   [FILLDATA] got current_bloc
[00:00:02.502] (30d57e000) INFO   [FILLDATA] got filepath
[00:00:02.503] (30d57e000) INFO   [FILLDATA] got nvim_instance
[00:00:02.503] (30d57e000) INFO   looped on key selected_interpreters
[00:00:02.503] (30d57e000) INFO   [FILLDATA] got selected interpreters
[00:00:02.503] (30d57e000) INFO   looped on key repl_enable
[00:00:02.503] (30d57e000) INFO   [FILLDATA] got repl enabled interpreters
[00:00:02.503] (30d57e000) INFO   looped on key repl_disable
[00:00:02.503] (30d57e000) INFO   [FILLDATA] got repl disabled interpreters
[00:00:02.503] (30d57e000) INFO   looped on key display
[00:00:02.503] (30d57e000) INFO   [FILLDATA] display type found : Ok(TerminalWithCode)
[00:00:02.504] (30d57e000) INFO   [FILLDATA] got display types
[00:00:02.504] (30d57e000) INFO   looped on key show_no_output
[00:00:02.504] (30d57e000) INFO   [FILLDATA] display type with 'no output'on found : Ok(Classic)
[00:00:02.504] (30d57e000) INFO   [FILLDATA] display type with 'no output'on found : Ok(TempFloatingWindow)
[00:00:02.504] (30d57e000) INFO   [FILLDATA] got show_no_output
[00:00:02.504] (30d57e000) INFO   looped on key inline_messages
[00:00:02.504] (30d57e000) INFO   [FILLDATA] got inline_messages setting
[00:00:02.504] (30d57e000) INFO   looped on key neovim_pid
[00:00:02.504] (30d57e000) INFO   [FILLDATA] got neovim_pid value setting: 29553
[00:00:02.505] (30d57e000) INFO   [FILLDATA] Done!
[00:00:02.505] (30d57e000) INFO   [OVERRIDE] No data to override
[00:00:02.505] (30d57e000) INFO   [RUN] filled dataholder
[00:00:02.505] (30d57e000) INFO   [RUN] created launcher
[00:00:02.505] (30d57e000) INFO   selected JS_TS_deno
[00:00:02.505] (30d57e000) INFO   [LAUNCHER] Selected interpreter: JS_TS_deno, at level Selected
[00:00:02.506] (30d57e000) INFO   Checking cli-args: []
[00:00:02.506] (30d57e000) INFO   REPL enabled
[00:00:02.506] (30d57e000) INFO   reading previous code
[00:00:02.506] (30d57e000) INFO   found interpreter_data
[00:00:02.506] (30d57e000) INFO   Deno kernel already running
[00:00:02.506] (30d57e000) INFO   javascript/typescript self.code) = console.log('asdf')
[00:00:02.507] (30d57e000) INFO   running launcher /Users/jeggers/.vim/plugged/sniprun/lua/../ressources/launcher_repl.sh
[00:00:02.508] (30d57e000) INFO   cmd status: Ok(Child { stdin: None, stdout: None, stderr: None, .. })
[00:00:02.509] (30d57e000) INFO   outfile : "/Users/jeggers/Library/Caches/sniprun/js-ts_deno/29553/fifo_repl/out_file"
[00:00:02.509] (30d57e000) INFO   searching for things between "sniprun_started_id=1" and "sniprun_finished_id=1"
[00:00:02.560] (30d57e000) INFO   errfile exists
[00:00:02.560] (30d57e000) INFO   err to display : "\n"
[00:00:02.560] (30d57e000) INFO   file exists
[00:00:02.561] (30d57e000) INFO   relevant Deno 1.25.0
exit using ctrl+d or close()
sniprun_started_id=1
asdf
sniprun_finished_id=1
[00:00:02.561] (30d57e000) INFO   file could be read : "Deno 1.25.0\nexit using ctrl+d or close()\nsniprun_started_id=1\nasdf\nsniprun_finished_id=1"
[00:00:02.561] (30d57e000) INFO   out found
[00:00:02.561] (30d57e000) INFO   [RUN] Interpreter return a result
[00:00:02.561] (30d57e000) INFO   Display type chosen: [TerminalWithCode]
[00:00:02.561] (30d57e000) INFO   message 'asdf' cleaned out
[00:00:02.563] (30d57e000) INFO   display terminal res = Ok(())
```

**Comment by michaelb** [comment] 2022-09-06 18:03
Nice :-)

(and the other fix about closing the fds behaves similarly on MacOS and linux, or so it looks like). I'll close this issue with the incoming 1.2.7 release

**Closed** 2022-09-06 22:25 UTC
Labels: bug

**Comment by convers39** [comment] 2022-10-16 07:27
Does this bug be fixed? Encountered today

<img width="499" alt="image" src="https://user-images.githubusercontent.com/42597395/196023676-46cadc3f-ee33-4930-bedb-82d83e3459f4.png">

**Comment by michaelb** [comment] 2022-10-16 09:44
This particular bug has been fixed for sure. If you can't figure out what's wrong from the [documentation](https://michaelb.github.io/sniprun/sources/interpreters/JS_TS_deno.html) ( also accessible at `:SnipInfo JS_TS_deno`), please open a new issue so I an help you from there
