### ISSUE TITLE
force interpreter when running a bloc ?

### ISSUE THREAD

**Issue by teto** [michaelb/sniprun#151] opened 2022-04-03 16:11 UTC
**Is your feature request related to a problem? Please describe.**
I am interested in the "babel"/orgmode integration of sniprun. I was able to run a bloc of bash code via `:SnipRun` with the cursor at the end of first line
```
#+begin_src sh 
echo "hello world"
#+end_src
```
I tried to do sthg similar with haskell:
```
#+begin_src haskell
putStrLn "hello world"
#+end_src
```
but I get `Failed to determine language of code bloc`. Can I force the repl in some way ? like `:SnipRun haskell`  ? 
Also the doc mentions it only supports line mode for haskell. How hard would it be to support bloc mode. I've got some colleagues that may be interested in the task (or I).

**Comment by michaelb** [comment] 2022-04-03 21:30
First, your questions

> Can I force the repl in some way ? like :SnipRun haskell 

No, but there I found a bug (that will be promptly adressed) in the Orgmode code bloc detection. For the time being, using #+BEGIN_SRC instead of the lowercase variant should make do. 

```
#+BEGIN_SRC haskell
putStrLn "hello world"      <- running Sniprun on this line works for me
#+END_SRC
```

>  .. only supports line mode for haskell.

Yes, and that's probably the cause of other problems (such as running from the first
`#+begin_src haskell` line, which is supposed to run the whole bloc but now completely fails). I hadn't tested quite thoroughly since only a handful of interpreters are only supported to level 'Line'.

> How hard would it be to support bloc mode

Bloc _should_ be very easy. I've made some interpreters in less than 10min, validation & tests included, and there have been some contributors that made their way through the CONTRIBUTING.md file successfully & without too much issues even without too familiar with Rust.

However, if during that frantic period when I was adding tons of languages to sniprun, I didn't make a Line bloc capable interpreter, it's because I stumbled on _something_ . To be honest, probably my unfamiliarity with the language in this case, but maybe a quirk of haskell that I gave up upon. 

You may want to start from 'scratch' (the src/interpreters/example.rs), or the current Haskell_original.rs interperter: it's currently so little-featured I don't think anyone will miss it.

**Comment by michaelb** [comment] 2022-04-13 21:31
#153 fixes the initial issue about code bloc delimiter detection and will be merged soon

Feel free to open a different issue (or submit a PR!) for haskell support

**Closed** 2022-04-14 10:19 UTC

**Comment by teto** [comment] 2022-04-14 13:42
ok thanks
