### ISSUE TITLE
REPL Python_original not working properly

### ISSUE THREAD

**Issue by mmazz** [michaelb/sniprun#129] opened 2021-12-15 19:44 UTC
**Describe the bug**
When I have REPL enable, it does not remember the variables i define.

* *To Reproduce**
I have this configuration:
`require'sniprun'.setup({
    selected_interpreters = {"Python3_original"},
    repl_enable = {"Python_original"},
    display = { "Terminal" } 
})`
When I run a python script line by line, it don't remember my variables.
If i run something like this line by line:
`import numpy as np`
`x = np.linespace(0,10,10)`
`print(x)`

I get:
`RuntimeError: NameError: name 'x' is no
t defined`

**Environment:**
 - Neovim version [e.g. v0.6.0]
- Arch Linux, 5.15.5
- GLIBC version 2.33

**Comment by michaelb** [comment] 2021-12-15 19:50
`repl_enable={"Python3_original"}`

looks better

And you can remove the -- terminal classic thing, -- is the comment delimiter in Lua

**Comment by michaelb** [comment] 2021-12-15 22:39
Unfortunately, I'm unable to reproduce, it works fine:
![Screenshot_66](https://user-images.githubusercontent.com/44144536/146275429-7f6e7e7e-718c-4f18-8276-902656203fe6.png)
(with this config:
```
require'sniprun'.setup({ selected_interpreters = {"Python3_original"}, repl_enable = {"Python3_original"}, display = { "Terminal" } })
```
One quirk related to our discussion on reddit might be worth mentionning, Python3_original in REPL mode doesn't allow to sniprun `plt.plot(data)` and `plt.show()` separately, you'll have to send them in at the same time/visual bloc

**Comment by mmazz** [comment] 2021-12-16 11:25
I try with Python_fifo, and it solves this issue but adds another.
After running SnipRun twice (the first is for the connection starts), it's gives me an syntax error. Then after running twice, it's start to work properly, including the error with Python3_original.

![exam](https://user-images.githubusercontent.com/32109098/146362802-e23bab5e-621b-4711-8267-e46fc65990ce.png)

**Comment by michaelb** [comment] 2021-12-16 11:33
I'll try to reproduce your issue, but mind that you don't need to send imports to sniprun

They will (should) be fetched automatically when needed

**Comment by mmazz** [comment] 2021-12-16 11:39
In Python3_fifo if i do not import it's tell me that np it's not defined (with Python3_original, works fine that perk).

**Comment by michaelb** [comment] 2021-12-16 15:38
Now that was a real bug😅

Thanks for reporting :-)

I found the bug (a quite tricky one) and Python3_fifo will be fixed soon, i'll close this issue when sniprun gets updated

**Closed** 2021-12-19 10:21 UTC
Labels: bug
