### ISSUE TITLE
some go code segment complie-time error 

### ISSUE THREAD

**Issue by edte** [michaelb/sniprun#172] opened 2022-07-01 11:58 UTC
**Describe the bug**
No matter what I choose to run, it will show complie-time error

**What do the bug concerns? Sniprun itself, a particular interpreter?**
When using other code, such as printing hello world, it works normally,But this code fails,I guess this syntax is not supported or not supported?

**To Reproduce**

just try to run this code

```
package main

import (
	"fmt"
	"path"
)

func main() {
	fmt.Println(path.Ext("a.go"))
}
```

![a](https://user-images.githubusercontent.com/50194671/176889695-16a3465e-4cb2-41ef-aae2-a1a2d0e76bca.gif)

**Expected behavior**
output:     go

**Environment:**
![image](https://user-images.githubusercontent.com/50194671/176889842-8ed78548-9425-4ae5-8310-4b26c71427eb.png)
![image](https://user-images.githubusercontent.com/50194671/176889868-8775a437-cb8f-4f67-b801-015da822a44f.png)
![image](https://user-images.githubusercontent.com/50194671/176889896-710234a9-3022-4755-9609-ef838776b818.png)

**Comment by edte** [comment] 2022-07-01 12:12
maybe this code also can't run
```
package main

import (
	"fmt"
	"hash/crc32"
)

func main() {
	t := crc32.MakeTable(0xD5828281)
	fmt.Printf("%08x\n", crc32.Checksum([]byte("hello world"), t))
}
```

**Comment by michaelb** [comment] 2022-07-01 12:37
Hey!

Well, it's not a bug but rather a missing "feature".

Go only has support up to 'Bloc' which means it can run blocs of adjacents lines that are semantically correct on their own.... So if you try to use an external package it's no surprise it'll fail.

Try a hello world to test ?


Selecting the whole file shouldn't really be the way to go, though some other languages can do that as sniprun can more easily detect that the entry point was included in the selection.

There are two things I can do, and I'll probably do both sooner rather than later:

- upgrade Go to the 'import' level where sniprun will automatically add the good imports.

- improve the entry point detection so you can run your imports along the main function

**Comment by michaelb** [comment] 2022-07-24 17:54
@edte 
with #174 I added Import support for Golang.
![Screenshot_125](https://user-images.githubusercontent.com/44144536/180659764-b345f163-35bc-4b5d-a6d9-c5cafd7ac0ca.png)

Your snippet now works as expected and no-too-strange corner cases should also work

Will be included into this evening's v1.2.6 release

**Closed** 2022-07-26 08:27 UTC
Labels: bug

**Comment by edte** [comment] 2022-07-26 12:37
i use nvim-lspconfig to manage nvim, and after i update this plugin, i got an error:

like this
```
Failes to install the jdtls server with the following error message: E5108: Error executing lua Vim:E475: Invalid value for argument cmd: 'sniprun'is not executable
```

by this error, i found target/release directory is no files, after reading souce code, i found when execute install.sh file,it depend on $1 parameter, so i manully execute `./install.sh v1.2.6`, it works.

so is there an error at Installation in READEME.md, may it should be `bash ./install.sh v1.2.6` ?

**Comment by michaelb** [comment] 2022-07-26 17:47
Ahaha you've debugged a bit _too much_

Yes, the install.sh script looks for a $1 variable, but it's to differentiate between "normal" install (download a binary from GitHub releases) and "dev" install (compile from source, longer and has prerequisites)

The actual value of the $1 arg has no importance


Maybe some networking thing failed during the download ? `checkhealth sniprun` might have debugged you but it looks like the issue  is resolved anyway
