### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by the-noob-coder69** [michaelb/sniprun#88] opened 2021-07-21 19:25 UTC
**Describe the bug**
I don't know what's happening but i am getting an error saying that there is no file or directory `/home/shantnu/.local/share/nvim/sit
e/pack/packer/start/sniprun/target/release/sniprun` even after i did ./install.sh manually (i forgot to add that line in my plugin manager)

**Expected behavior**
It should have run properly without any errors

**Screenshots**
![wth](https://user-images.githubusercontent.com/76793870/126547477-fb2cc69d-400a-4ea6-b7e9-ea217cf34e30.png)

**Environment:**
 - Neovim v0.6.0-dev

**Comment by michaelb** [comment] 2021-07-21 19:33
duplicate of #87 , see you there

**Closed by michaelb** 2021-07-21 19:33 UTC
Labels: bug

**Comment by the-noob-coder69** [comment] 2021-07-22 07:17
oh lol i will blame my internet for that it said cant reach the server so i got back to the page where i was creating the issue and my cache was saved and i was a bit lazy so i skipped `Sniprun says` ^_^;
