### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by ahmedkhalf** [michaelb/sniprun#65] opened 2021-04-24 17:44 UTC
**Describe the bug**
So I download the plugin using: `Plug 'michaelb/sniprun', {'do': 'bash install.sh'}`. Then restart nvim then execute `:Sniprun`  --> nothing... no errors just nothing. OKAY. So now I execute `:Snipinfo` --> nothing... no errors just nothing.

**Expected behavior**
I just want my code to run

**Environment:**
 - Latest Neovim Nightly with linux Ubuntu machine and cargo installed.

**Comment by michaelb** [comment] 2021-04-24 18:48
yep, that's a known issue but I guess I should make it more obvious.

Silent fail is a consequence of the precompiled binary being incompatible with your system (sometimes uncommon distros or Mac) (are you on Mac?)

The new `:checkhealth sniprun` feature should provide solid clues about what went wrong. You arleady have the rust toolchain installed, so I recommend you compile the core sniprun binary locally: in order to do that, run either `bash ./install.sh 1` or `cargo build --release` as install script, instead of `bash ./install.sh`

**Comment by michaelb** [comment] 2021-04-24 18:57
(also but I think you got this right or you'd have had a 'undefined command' error, but the shorthands are `:SnipRun` and `:SnipInfo` with capitals )

**Comment by ahmedkhalf** [comment] 2021-04-26 15:35
> Silent fail is a consequence of the precompiled binary being incompatible with your system, for some reason I can't fully understand, but happens with Mac, or ARM machines, or i don't know.

I am actually on Linux(Ubuntu) so my guess is that you compiled it on arch for example and that made it incompatible on my distro, so maybe you can package it as an AppImage or build it for every distro using specialized tools (LXC-Containers ?).

> yep, that's a known issue but I guess I should make it more obvious.

> The new `:checkhealth sniprun` feature should provide solid clues about what went wrong. You arleady have the rust toolchain installed, so I recommend you compile the core sniprun binary locally: in order to do that, run either `bash ./install.sh 1` or `cargo build --release` as install script, instead of `bash ./install.sh`

With all my respect, I don't think making it obvious is the correct solution here (although could be part of the solution). Instead of telling the user to compile the program on his machine, it should check if cargo is installed and then build the program directly within vim. I suggest you have a look at what vim clap does because I believe it is the correct way of handling such issue.

**Comment by michaelb** [comment] 2021-04-26 23:18
Your guess is right, though binary compatibility between contemporate distros is usually not an issue.

I got a look at vim-clap, but the build system is so incredibly complicated I don't know where to begin to replicate such a thing.
I don't think (unless some assumptions are challenged) I will provide such auto-compilation feature, because:
- I can't test anything, because there are many various laptops/architectures/distros which will probably behave differently
- The logic detecting whether the binary crashes at start is very, very far from perfect. Automating sniprun's compilation could have disastrous consequences (like recompiling everytime sniprun is launched even though the binary runs fine, but wasn't detected as such)

**Comment by michaelb** [comment] 2021-04-29 18:11
Oh god, I get it.

A very embarrasing typo indeed is the root cause of this issue, because otherwise binary compatibility between recent distros is a given ,right? Now fixed in v0.5.4, and regarding the anwser I provided earlier, I think this issue can be closed

**Closed** 2021-04-29 18:11 UTC
Labels: bug
